building_data = {
    "road_straight": {
        "Information": ["Cost", "Maintenance"],
        'Type': "road_straight",
        'Category': "Roads",
        'Name': 'Straight Road',
        'Description': 'Like a laser beam on asphalt, straight from A to B',
        'Cost': 25,
        'Maintenance': 2,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "road_crossing": {
        "Information": ["Cost", "Maintenance"],
        'Type': "road_crossing",
        'Category': "Roads",
        'Name': 'Road Crossing',
        'Description': "'The human highway connection.' Look both ways!",
        'Cost': 50,
        'Maintenance': 5,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "road_uturn": {
        "Information": ["Cost", "Maintenance"],
        'Type': "road_uturn",
        'Category': "Roads",
        'Name': 'U-Turn',
        'Description': 'Because sometimes the best path is the one you just passed',
        'Cost': 20,
        'Maintenance': 2,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "road_curved": {
        "Information": ["Cost", "Maintenance"],
        'Type': "road_curved",
        'Category': "Roads",
        'Name': 'Curved Road',
        'Description': "Embrace the bends. Straight-line monotony is so last road",
        'Cost': 35,
        'Maintenance': 3,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "road_3way": {
        "Information": ["Cost", "Maintenance"],
        'Type': "road_3way",
        'Category': "Roads",
        'Name': '3-Way Intersection',
        'Description': 'Turning points, twists, and tales unfold in threes',
        'Cost': 60,
        'Maintenance': 6,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_3way_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_3way_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_3way_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_3way_w.png"}}},
    "road_4way": {
        "Information": ["Cost", "Maintenance"],
        'Type': "road_4way",
        'Category': "Roads",
        'Name': '4-Way Intersection',
        'Description': 'Four ways, one decision: Crossroad carnival!',
        'Cost': 80,
        'Maintenance': 8,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_4way_nsew.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_4way_nsew.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_4way_nsew.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/road/road_4way_nsew.png"}}},
    "util_wind": {
        "Information": ["Cost", "Maintenance", "Revenue"],
        'Type': "util_wind",
        'Category': "Utilities",
        'Name': 'Wind Turbine',
        'Description': "Like a record, baby, right 'round, 'round, 'round",
        'Cost': 250,
        'Maintenance': 15,
        'Revenue': 25, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "util_powe": {
        "Information": ["Cost", "Maintenance", "Revenue"],
        'Type': "util_powe",
        'Category': "Utilities",
        'Name': 'Power Plant',
        'Description': "Watt's up? Not your bill, thank the Power Plant later",
        'Cost': 1250,
        'Maintenance': 5,
        'Revenue': 35, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "util_wate": {
        "Information": ["Cost", "Maintenance", "Revenue"],
        'Type': "util_wate",
        'Category': "Utilities",
        'Name': 'Water Tower',
        'Description': "Keeping water high, and expectations around the same",
        'Cost': 200,
        'Maintenance': 15,
        'Revenue': 20, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "util_tre": {
        "Information": ["Cost", "Maintenance", "Revenue"],
        'Type': "util_tre",
        'Category': "Utilities",
        'Name': 'Water Treatment Plant',
        'Description': "Turning your gold liquid to liquid gold",
        'Cost': 550,
        'Maintenance': 5,
        'Revenue': 35, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "util_land": {
        "Information": ["Cost", "Maintenance", "Revenue"],
        'Type': "util_land",
        'Category': "Utilities",
        'Name': 'Landfill Site',
        'Description': "Collecting memories you'd rather forget",
        'Cost': 550,
        'Maintenance': 5,
        'Revenue': 35, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "util_cell": {
        "Information": ["Cost", "Maintenance", "Revenue"],
        'Type': "util_cell",
        'Category': "Utilities",
        'Name': 'Cell Tower',
        'Description': "Emitting signals and conspiracies circa 2023",
        'Cost': 550,
        'Maintenance': 5,
        'Revenue': 35, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "serv_city": {
        "Information": ["Cost", "Maintenance", "Revenue"],
        'Type': "serv_city",
        'Category': "Services",
        'Name': 'City Hall',
        'Description': "Home of fading dreams and questionable decisions",
        'Cost': 550,
        'Maintenance': 5,
        'Revenue': 35, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
        "resi1": {
        "Information": ["Cost", "Revenue"],
        'Type': "resi1",
        'Category': "Residential",
        'Name': 'Home',
        'Description': '- A typical home.',
        'Cost': 80,
        'Maintenance': 250,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {"north": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_n.png"},
                    "south": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_s.png"},
                    "east": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_e.png"},
                    "west": {'Width': 1,'Height': 1,'ImagePath': "images/resi/resi1_w.png"}}},
    "com2": {
        "Information": ["Cost", "Revenue", "Maintenance"],
        'Type': "com2",
        'Category': "Commercial",
        'Name': 'Shop',
        'Description': '- Shop. How awesome!',
        'Cost': 15000,
        'Maintenance': 250,
        'Revenue': 0, 
        'Population': 0,
        "Rotations": {
            "north": {
                'Width': 4,
                'Height': 3,
                'ImagePath': "images/resi/com2_n.png"
            },
            "south": {
                'Width': 4,
                'Height': 3,
                'ImagePath': "images/resi/com2_s.png"
            },
            "east": {
                'Width': 3,
                'Height': 4,
                'ImagePath': "images/resi/com2_e.png"
            },
            "west": {
                'Width': 3,
                'Height': 4,
                'ImagePath': "images/resi/com2_w.png"
            }
        }
    },
}